// Simple production-ready API: SQLite + JWT auth.
//
//	@title			Auth API
//	@version		1.0
//	@description	Register, login, and profile with JWT. All responses use envelope: { "data": ..., "error": "" }.
//	@host			localhost:8080
//	@BasePath		/
//	@securityDefinitions.apikey	BearerAuth
//	@in							header
//	@name						Authorization
package main

import (
	"log"
	"os"
	"os/signal"
	"syscall"

	"app/config"
	_ "app/docs" // generated by swag init
	"app/handlers"
	"app/middleware"
	"app/store/sqlite"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func main() {
	cfg := config.Load()
	db, err := sqlite.New(cfg.DBPath)
	if err != nil {
		log.Fatalf("database: %v", err)
	}
	defer db.Close()

	if os.Getenv("GIN_MODE") != "release" {
		gin.SetMode(gin.DebugMode)
	}
	r := gin.Default()
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	authHandler := &handlers.Auth{Repo: db, Config: cfg}
	profileHandler := &handlers.Profile{Repo: db}

	r.POST("/register", authHandler.Register)
	r.POST("/login", authHandler.Login)

	auth := r.Group("/")
	auth.Use(middleware.Auth(cfg))
	{
		auth.GET("/profile", profileHandler.Profile)
	}

	// Graceful shutdown
	go func() {
		log.Printf("listening on :%s", cfg.Port)
		if err := r.Run(":" + cfg.Port); err != nil {
			log.Printf("serve: %v", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("shutting down")
}
