// Package docs Code generated by swaggo/swag. DO NOT EDIT.
// Regenerate with: swag init -g main.go --parseDependency --parseInternal
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}",
        "host": "{{.Host}}",
        "basePath": "{{.BasePath}}"
    },
    "paths": {
        "/register": {
            "post": {
                "summary": "Register a new user",
                "tags": ["auth"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "description": "Register payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": { "$ref": "#/definitions/handlers.RegisterRequest" }
                    }
                ],
                "responses": {
                    "201": { "description": "Created", "schema": { "$ref": "#/definitions/response.RegisterResponse" } },
                    "400": { "description": "Invalid input", "schema": { "$ref": "#/definitions/response.ErrorResponse" } },
                    "409": { "description": "Email already registered", "schema": { "$ref": "#/definitions/response.ErrorResponse" } }
                }
            }
        },
        "/login": {
            "post": {
                "summary": "Login",
                "tags": ["auth"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": { "$ref": "#/definitions/handlers.LoginRequest" }
                    }
                ],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/response.LoginResponse" } },
                    "400": { "description": "Invalid input", "schema": { "$ref": "#/definitions/response.ErrorResponse" } },
                    "401": { "description": "Invalid credentials", "schema": { "$ref": "#/definitions/response.ErrorResponse" } }
                }
            }
        },
        "/profile": {
            "get": {
                "summary": "Get current user profile",
                "tags": ["auth"],
                "security": [{ "BearerAuth": [] }],
                "produces": ["application/json"],
                "responses": {
                    "200": { "description": "OK", "schema": { "$ref": "#/definitions/response.ProfileResponse" } },
                    "401": { "description": "Unauthorized", "schema": { "$ref": "#/definitions/response.ErrorResponse" } },
                    "404": { "description": "User not found", "schema": { "$ref": "#/definitions/response.ErrorResponse" } }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "definitions": {
        "handlers.RegisterRequest": {
            "type": "object",
            "required": ["email", "password"],
            "properties": {
                "email": { "type": "string", "example": "user@example.com" },
                "password": { "type": "string", "minLength": 8 }
            }
        },
        "handlers.LoginRequest": {
            "type": "object",
            "required": ["email", "password"],
            "properties": {
                "email": { "type": "string" },
                "password": { "type": "string" }
            }
        },
        "response.RegisterResponse": {
            "type": "object",
            "properties": {
                "data": { "$ref": "#/definitions/response.RegisterData" },
                "error": { "type": "string" }
            }
        },
        "response.RegisterData": {
            "type": "object",
            "properties": { "id": { "type": "integer" }, "email": { "type": "string" } }
        },
        "response.LoginResponse": {
            "type": "object",
            "properties": {
                "data": { "$ref": "#/definitions/response.LoginData" },
                "error": { "type": "string" }
            }
        },
        "response.LoginData": {
            "type": "object",
            "properties": {
                "token": { "type": "string" },
                "user": { "$ref": "#/definitions/response.UserPublic" }
            }
        },
        "response.UserPublic": {
            "type": "object",
            "properties": {
                "id": { "type": "integer" },
                "email": { "type": "string" },
                "created_at": { "type": "string", "format": "date-time" }
            }
        },
        "response.ProfileResponse": {
            "type": "object",
            "properties": {
                "data": { "$ref": "#/definitions/response.UserPublic" },
                "error": { "type": "string" }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": { "data": {}, "error": { "type": "string" } }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Auth API",
	Description:       "Register, login, and profile with JWT. All responses use envelope: { \"data\": ..., \"error\": \"\" }.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
